;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_i
	.export		_main

.segment	"BSS"

_i:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$03
	lda     #$91
	sta     _i
	stx     _i+1
L0002:	lda     _i
	ldx     _i+1
	cmp     #$9B
	txa
	sbc     #$03
	bvc     L0009
	eor     #$80
L0009:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0004
	jmp     L0003
L0004:	lda     _i
	ldx     _i+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     _i
	stx     _i+1
	lda     regsave
	ldx     regsave+1
	jmp     L0002
L0003:	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

