#!/bin/bash
#set -x
handindir=$1


if [[ -z $handindir ]]
then
   echo "USAGE: $(basename $0) <directory to place tar files>"
   exit -1
fi

if [[ ! -d $handindir ]]
then
   echo "ERROR: $handindir does not exist or is not a directory"
   exit -1
fi

find /cs/course/cs210/current/homework/spool  -name '6502.t*' | while read file
do
    cfile=$(basename $file)
    student=${file##/cs/course/cs210/current/homework/spool/}
    student=${student%%/*}
    handin=${handindir}/${student}_${cfile}
#    echo $file '->' $handin
    
    if file -b $file | grep -q gzip
    then
       echo "$handin ($file) is a gzip file unziping"
       gunzip -c $file  > ${handindir}/${student}_6502.tar
       handin=${handindir}/${student}_6502.tar
    else
          cp $file $handin
    fi

    if ! file -b $handin | grep -q tar
    then
       echo "WARNING: $handin not a tar file"
    fi
done