#!/bin/bash
#set -x

export cmdpid
export sleeppid
export mypid
export timeout=120

export TESTS="compile:10 memcpy:40 concpy:50 unknown1:100 unknown2:51"

function USAGE
{
    echo "$(basename $0) <handindir> <gradesdir>"
}

function killchildren 
{
  ppid=$1
  if [[ -z $ppid ]]
  then
    ppid=$$
  fi
  children="$(ps --ppid $ppid -o pid --no-headings)" 
  for pid in $children
  do
    if [[ -n $pid ]]
    then
      killchildren $pid
      kill -9 $pid > /dev/null 2>&1
    fi
  done
}

function deadline
{
  trap - SIGCHLD

  if kill -0 $cmdpid >/dev/null 2>&1 ; then
    killchildren $cmdpid
    kill $cmdpid
  fi
  if kill -0 $sleeppid >/dev/null 2>&1 ; then
    kill $sleeppid
  fi
}

function dograde
{
  dir=$1
  src=$2
  logfile=$3
  score=0

  for t in $TESTS
  do
    points=${t##*:}
    test=${t%%:*}
    echo "doing: $test for $points" >> ${logfile}

    
    set -b
    set -m 
    mypid=$$
    make -C $src $test >${dir}/grade.${test}.log 2>&1 &
    cmdpid=$!
    /bin/sleep $timeout &
    sleeppid=$!

    trap deadline SIGCHLD
    wait $cmdpid

    trap - SIGCHLD
    kill $sleeppid >/dev/null 2>&1
    
    if  grep PASS ${dir}/grade.${test}.log >> ${logfile} 2>&1
    then
      score=$((score + $points))
    fi
  done
  info=$($src/6502 2>/dev/null)
  echo $info $score
}

export srcdir=$(readlink -e ..)
export handindir=$(readlink -e $1)
export gradedir=$(readlink -e $2)

if [[ -z $handindir ]]
then
  USAGE
  exit -1
fi

if [[ -z $gradedir ]]
then
  USAGE
  exit -1
fi

if [[ ! -d $gradedir ]]
then
  echo "ERROR: $gradedir does not exist or is not a directory"
  exit -1
fi


for file in ${handindir}/* 
do
  export student=$(basename ${file%%_*})
  echo "grading $student: $file"
  if mkdir ${gradedir}/${student}
  then
     sdir=${gradedir}/${student}
     hdir=${sdir}/handin
     tdir=${sdir}/tdir
     log=${sdir}/log
     mkdir $hdir > $log 2>&1 
     mkdir $tdir >> $log 2>&1 
     (cd $hdir; tar -xvf ${file}) >> $log 2>&1
     # put student code into test dir
     find ${hdir} -name '*.[ch]' | while read sfile
     do
       cp $sfile $tdir
     done >> $log 2>&1 

     # put standard apps dir, Makefile, img and main.c into test dir
     cp -r $srcdir/apps $tdir >> $log 2>&1 
     cp $srcdir/Makefile $tdir >> $log 2>&1 
     cp $srcdir/img $tdir >> $log 2>&1 
     cp $srcdir/main.c $tdir >> $log 2>&1 

     grade="$(dograde $sdir $tdir $log )"
     echo "$grade" >> $log
     echo "$grade" > ${sdir}/grade.txt
     echo "$grade" >> ${gradedir}/report.txt
  else
     echo "ERROR: not able to mkdir ${gradedir/$student}"   
  fi
done




