;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.export		_main

.segment	"RODATA"

L0019:
	.byte	$69,$3D,$25,$6C,$64,$2C,$20,$6A,$3D,$25,$6C,$64,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp8
	ldy     #$04
	lda     #$01
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	iny
	sta     (sp),y
L0002:	ldy     #$07
	jsr     ldeaxysp
	cmp     #$20
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L0003
	ldy     #$07
	jsr     ldeaxysp
L001F:	jsr     steax0sp
	jsr     ldeax0sp
	cmp     #$02
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcc     L0004
	jsr     ldeax0sp
	ldx     #$00
	and     #$01
	jsr     push0ax
	txa
	jsr     toseqeax
	beq     L0011
	jsr     ldeax0sp
	jsr     shreax1
	jmp     L001F
L0011:	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$00
	lda     #$03
	jsr     tosumul0ax
	ldy     #$01
	jsr     inceaxy
	jmp     L001F
L0004:	ldy     #$07
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$04
	jsr     steaxysp
	jsr     resteax
	jmp     L0002
L0003:	lda     #<(L0019)
	ldx     #>(L0019)
	jsr     pushax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$0A
	jsr     _cprintf
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp8

.endproc

