/*
 * test program for the cprintf() function
 * (for the \r and \n special operators)
 * CPG
 *
 * The output generated by this program should look
 * like this:
 *
 * ---- top of screen --------
 * 12345
 *      67890
 *
 *
 * 67890
 *
 * hit return to exit....
 .
 .
 .
 * ---- bottom of screen -----
 */

#include <conio.h>

int main(void)
{
	cprintf("12345\n");
	cprintf("67890\n");
	cprintf("12345\r");
	cprintf("67890\r");
	cprintf("\n\n");
	cprintf("hit return to exit....\n");
	cprintf("\nSUCCESS\n");
	return(0);
}
