;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.import		_cscanf
	.export		_fib
	.export		_main

.segment	"RODATA"

L0021:
	.byte	$25,$6C,$75,$0A,$00
L001A:
	.byte	$2D,$31,$0A,$00
L0012:
	.byte	$25,$6C,$64,$00

; ---------------------------------------------------------------
; unsigned long __near__ fib (long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fib: near

.segment	"CODE"

	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jsr     toseqeax
	beq     L0002
	ldx     #$00
	txa
	jmp     incsp4
L0002:	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$01
	jsr     toseqeax
	beq     L0005
	ldx     #$00
	lda     #$01
	jmp     incsp4
L0005:	jsr     ldeax0sp
	ldy     #$01
	jsr     deceaxy
	jsr     pusheax
	jsr     _fib
	jsr     pusheax
	ldy     #$07
	jsr     ldeaxysp
	ldy     #$02
	jsr     deceaxy
	jsr     pusheax
	jsr     _fib
	jsr     tosaddeax
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp8
L000C:	lda     #<(L0012)
	ldx     #>(L0012)
	jsr     pushax
	lda     sp
	ldx     sp+1
	clc
	adc     #$06
	bcc     L0015
	inx
L0015:	jsr     pushax
	ldy     #$04
	jsr     _cscanf
	cpx     #$00
	bne     L0025
	cmp     #$00
	beq     L0026
L0025:	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$30
	jsr     tosgeeax
	beq     L0017
	lda     #<(L001A)
	ldx     #>(L001A)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	jmp     L000C
L0017:	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	jsr     _fib
	jsr     steax0sp
	lda     #<(L0021)
	ldx     #>(L0021)
	jsr     pushax
	ldy     #$05
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	jsr     _cprintf
	jmp     L000C
L0026:	jmp     incsp8

.endproc

