;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.import		_cscanf
	.export		_fibtbl
	.export		_fib
	.export		_main

.segment	"DATA"

_fibtbl:
	.dword	$00000000
	.dword	$00000001
	.dword	$00000001
	.dword	$00000002
	.dword	$00000003
	.dword	$00000005
	.dword	$00000008
	.dword	$0000000D
	.dword	$00000015
	.dword	$00000022
	.dword	$00000037
	.dword	$00000059
	.dword	$00000090
	.dword	$000000E9
	.dword	$00000179
	.dword	$00000262
	.dword	$000003DB
	.dword	$0000063D
	.dword	$00000A18
	.dword	$00001055
	.dword	$00001A6D
	.dword	$00002AC2
	.dword	$0000452F
	.dword	$00006FF1
	.dword	$0000B520
	.dword	$00012511
	.dword	$0001DA31
	.dword	$0002FF42
	.dword	$0004D973
	.dword	$0007D8B5
	.dword	$000CB228
	.dword	$00148ADD
	.dword	$00213D05
	.dword	$0035C7E2
	.dword	$005704E7
	.dword	$008CCCC9
	.dword	$00E3D1B0
	.dword	$01709E79
	.dword	$02547029
	.dword	$03C50EA2
	.dword	$06197ECB
	.dword	$09DE8D6D
	.dword	$0FF80C38
	.dword	$19D699A5
	.dword	$29CEA5DD
	.dword	$43A53F82
	.dword	$6D73E55F
	.dword	$B11924E1

.segment	"RODATA"

L004A:
	.byte	$25,$6C,$75,$0A,$00
L0043:
	.byte	$2D,$31,$0A,$00
L003B:
	.byte	$25,$6C,$64,$00

; ---------------------------------------------------------------
; unsigned long __near__ fib (long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fib: near

.segment	"CODE"

	jsr     ldeax0sp
	jsr     aslax2
	clc
	adc     #<(_fibtbl)
	tay
	txa
	adc     #>(_fibtbl)
	tax
	tya
	jsr     ldeaxi
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp8
L0035:	lda     #<(L003B)
	ldx     #>(L003B)
	jsr     pushax
	lda     sp
	ldx     sp+1
	clc
	adc     #$06
	bcc     L003E
	inx
L003E:	jsr     pushax
	ldy     #$04
	jsr     _cscanf
	cpx     #$00
	bne     L004E
	cmp     #$00
	beq     L004F
L004E:	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$30
	jsr     tosgeeax
	beq     L0040
	lda     #<(L0043)
	ldx     #>(L0043)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	jmp     L0035
L0040:	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	jsr     _fib
	jsr     steax0sp
	lda     #<(L004A)
	ldx     #>(L004A)
	jsr     pushax
	ldy     #$05
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	jsr     _cprintf
	jmp     L0035
L004F:	jmp     incsp8

.endproc

