;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.export		_str
	.export		_main

.segment	"DATA"

_str:
	.byte	$4D,$79,$20,$73,$74,$72,$69,$6E,$67,$2E,$00
	.res	69,$00

.segment	"RODATA"

L0017:
	.byte	$73,$69,$7A,$65,$6F,$66,$28,$69,$6E,$74,$29,$3D,$25,$64,$20,$73
	.byte	$69,$7A,$65,$6F,$66,$28,$6C,$6F,$6E,$67,$29,$3D,$25,$64,$20,$73
	.byte	$69,$7A,$65,$6F,$66,$28,$75,$6E,$73,$69,$67,$6E,$65,$64,$20,$6C
	.byte	$6F,$6E,$67,$29,$3D,$25,$64,$0A,$00
L0007:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$21,$21,$21,$0A,$00
L000E:
	.byte	$69,$3D,$25,$64,$20,$28,$25,$78,$29,$0A,$00
L0013:
	.byte	$73,$74,$72,$3D,$25,$73,$0A,$00
L000A:
	.byte	$63,$3D,$25,$63,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$61
	jsr     pusha
	lda     #$2D
	jsr     pusha0
	lda     #<(L0007)
	ldx     #>(L0007)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	lda     #<(L000A)
	ldx     #>(L000A)
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
	lda     #<(L000E)
	ldx     #>(L000E)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
	jsr     _cprintf
	lda     #<(L0013)
	ldx     #>(L0013)
	jsr     pushax
	lda     #<(_str)
	ldx     #>(_str)
	jsr     pushax
	ldy     #$04
	jsr     _cprintf
	lda     #<(L0017)
	ldx     #>(L0017)
	jsr     pushax
	lda     #$02
	jsr     pusha0
	lda     #$04
	jsr     pusha0
	jsr     pusha0
	ldy     #$08
	jsr     _cprintf
	ldx     #$00
	txa
	jmp     incsp3

.endproc

