;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.export		_main

.segment	"RODATA"

L000D:
	.byte	$69,$3D,$25,$75,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$03
	jsr     pusha0
L0003:	ldy     #$00
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L0011
	lda     #<(L000D)
	ldx     #>(L000D)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$04
	jsr     _cprintf
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L000B
	dex
L000B:	jsr     stax0sp
	jmp     L0003
L0011:	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp2

.endproc

