;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_src
	.export		_dst
	.export		_main

.segment	"DATA"

_src:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$00

.segment	"BSS"

_dst:
	.res	12,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
L0006:	lda     #<(_dst)
	ldx     #>(_dst)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L000C
	inx
L000C:	jsr     pushax
	ldy     #$02
	lda     (sp),y
	tay
	lda     _src,y
	ldy     #$00
	jsr     staspidx
	ldy     #$00
	lda     (sp),y
	tay
	ldx     #$00
	lda     _src,y
	beq     L0017
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$01
	sta     (sp),y
	jmp     L0006
L0017:	jmp     incsp1

.endproc

