;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.export		_main

.segment	"RODATA"

L000D:
	.byte	$25,$6C,$64,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp8
	ldy     #$04
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	iny
	sta     (sp),y
L0002:	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$03
	jsr     toslteax
	beq     L0003
	ldy     #$07
	jsr     ldeaxysp
	jsr     steax0sp
	lda     #<(L000D)
	ldx     #>(L000D)
	jsr     pushax
	ldy     #$05
	jsr     ldeaxysp
	ldy     #$0A
	jsr     inceaxy
	jsr     pusheax
	ldy     #$06
	jsr     _cprintf
	ldy     #$07
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$04
	jsr     steaxysp
	jsr     resteax
	jmp     L0002
L0003:	ldx     #$00
	txa
	jmp     incsp8

.endproc

