#!/bin/bash

bin=~/data/bin
inputs=../inputs

exp=$1
outbin=$2

if [ $# -ne 2 ]; then
  echo "USAGE: $0 [exp] [output binary file]"
  exit 0
fi

if [ -f $inputs/*.dat ]; then
  /usr/bin/time -o time.info ~/6502/6502 -t sv -o $outbin -p $exp.stdout -s $exp.initsv_finalsv -r $exp.opcodes $inputs/$exp.img $exp.oimg < $inputs/*.dat 2> $exp.stderr
else
  /usr/bin/time -o time.info ~/6502/6502 -t sv -o $outbin -p $exp.stdout -s $exp.initsv_finalsv -r $exp.opcodes $inputs/$exp.img $exp.oimg 2> $exp.stderr
fi

