#!/bin/bash

diff=$1
addr=0
numbytes=2

if [[ ! -a $diff ]]; then
  echo "USAGE: $0 [diff file]"
  exit 0
fi

((addr*=8))
((endaddr=addr+numbytes*8))

((inst=1))
while read -a diffarray; do
  ((sum=0))
  for ((i=0; i<${#diffarray[@]}; i++)); do
    if [ ${diffarray[$i]} -ge $addr ] && [ ${diffarray[$i]} -lt $endaddr ]; then
      ((sum+=1<<${diffarray[$i]}))
    fi
  done
  echo $inst $sum
  ((inst++))
done < $diff

