#!/bin/bash

if [ $# -ne 5 ]; then
  echo "USAGE: $0 [seq1 file] [seq2 file] [seq3 file] [seq4 file] [output pdf]"
  exit 0
fi

seq1=$1
seq2=$2
seq3=$3
seq4=$4
pdf=$5

echo "x1=load('$seq1.x');"
echo "y1=load('$seq1.y');"
echo "x2=load('$seq2.x');"
echo "y2=load('$seq2.y');"
echo "x3=load('$seq3.x');"
echo "y3=load('$seq3.y');"
echo "x4=load('$seq4.x');"
echo "y4=load('$seq4.y');"

echo "f=figure(1);"
echo "set(f,'visible','off');"

echo "hold off;"
echo "semilogy(x1,y1,'r.');"
echo "hold on;"
echo "semilogy(x2,y2,'m.');"
echo "hold on;"
echo "semilogy(x3,y3,'b.');"
echo "hold on;"
echo "semilogy(x4,y4,'g.');"
#echo "hold off;"
#echo "loglog([${exp}x(1);${exp}x(1)],[${exp}ymin(1);${exp}y(1)],'r-');"
#echo "for v=2:rows(${exp}x),"
#echo "  hold on;"
#echo "  loglog([${exp}x(v);${exp}x(v)],[${exp}ymin;${exp}y(v)],'r-');"
#echo "endfor;"

echo "axis([1,max([max(x1),max(x2),max(x3),max(x4)]),0.5,max([max(y1),max(y2),max(y3),max(y4)])]);"
echo "xlabel('length');"
echo "ylabel('count');"

echo "H=6; W=6; B=0.2;"
echo "set(f,'PaperSize',[H,W]);"
echo "set(f,'PaperPosition',[0,0,H,W]);"
echo "ax=gca();"
echo "print(f,'$pdf','-dpdf');"
